import {useEffect,useMemo,useRef,useState,type FormEvent} from 'react';
import {ArrowRight,Columns2,Download,Info,Pause,Play,RotateCcw,SkipForward,Upload,Zap} from 'lucide-react';
import {CompanyDatasetProvider,fingerprint} from '../data/company-datasets';
import {constructMachine,getNode} from '../translation/construct';
import {sectors} from '../sectors';
import type {CompanyDataset,CompanyScenario,MachineDefinition} from '../ontology/types';
import {suggestedScenario,simulateCompany,validateCompanyScenario} from '../simulation/company';
import CompanyMachine,{showValue} from './CompanyMachine';
import CompanyInspector from './CompanyInspector';
import Gauge from './Gauge';
const provider=new CompanyDatasetProvider();const names=['BASE','BULL','BEAR','CUSTOM'] as const;type Name=typeof names[number];type Scenarios=Record<Name,CompanyScenario>;
const defaults=(m:MachineDefinition):Scenarios=>Object.fromEntries(names.map(n=>[n,suggestedScenario(m)])) as Scenarios;
function descendants(m:MachineDefinition,start:string){const seen=new Set<string>(),queue=[start];while(queue.length){const key=queue.shift()!;if(seen.has(key))continue;seen.add(key);m.edges.filter(e=>e.from===key).forEach(e=>queue.push(e.to));}return [...seen];}
export default function CompanyWorkbench({manual,initialTicker='MSFT'}:{manual:()=>void;initialTicker?:string}){
 const [dataset,setDataset]=useState<CompanyDataset|null>(null),[period,setPeriod]=useState(0),[ticker,setTicker]=useState(initialTicker),[error,setError]=useState(''),[loading,setLoading]=useState(false);const serial=useRef(0);
 async function load(value:string){const sequence=++serial.current;setLoading(true);setError('');try{const data=await provider.getCompany(value);if(sequence!==serial.current)return;setDataset(data);setTicker(data.ticker);setPeriod(0)}catch(e){if(sequence===serial.current)setError(e instanceof Error?e.message:String(e))}finally{if(sequence===serial.current)setLoading(false)}}
 useEffect(()=>{void load(initialTicker);return()=>{serial.current++}},[initialTicker]);
 return <main className="app-shell v2-app"><header className="masthead"><div className="brand"><div className="edition">ECONOMIC SYSTEMS LAB <span>COMPANY → MACHINE / V2</span></div><h1>The Going Concern Machine</h1><p>Understand the business. Operate the economics.</p></div><form className="ticker-form" onSubmit={e=>{e.preventDefault();void load(ticker)}}><label htmlFor="company-ticker">LOAD A BUSINESS</label><div><input id="company-ticker" placeholder="MSFT, WMT, JPM" value={ticker} maxLength={10} onChange={e=>setTicker(e.target.value.toUpperCase())}/><button disabled={loading}>{loading?'Building…':'Construct'}<ArrowRight size={14}/></button></div><span>Three verified models · dated annual snapshots</span></form></header>
 <nav className="company-picker" aria-label="Business models"><div>{[['MSFT','Software + cloud'],['WMT','Retail'],['JPM','Banking']].map(([symbol,label])=><button key={symbol} aria-pressed={dataset?.ticker===symbol} onClick={()=>void load(symbol)}><strong>{symbol}</strong><span>{label}</span></button>)}</div><button className="text-button" onClick={manual}>Build a hypothetical business <ArrowRight size={13}/></button></nav>
 {error&&<div className="notice" role="alert">{error}</div>}{loading&&<div className="notice" role="status">Constructing the company’s economic machine…</div>}
 {dataset?<><div className="historical-strip"><div><span className="eyebrow">REPORTED HISTORY</span><strong>{dataset.name}</strong></div><div role="group" aria-label="Historical fiscal year">{dataset.periods.map((p,i)=><button key={p.period} aria-pressed={period===i} onClick={()=>setPeriod(i)}>FY{p.fiscalYear}<small>{p.period}</small></button>)}</div><span>Available annual periods only</span></div><CompanySession key={fingerprint(dataset,dataset.periods[period].period)} dataset={dataset} periodIndex={period}/></>:!loading?<div className="empty-state">Select one of the three verified businesses above.</div>:null}
 <footer className="page-footer"><span>THE MACHINE CONTINUES ONLY WHILE IT CREATES, CAPTURES AND REINVESTS ENOUGH ECONOMIC VALUE.</span><span>Public-company analysis · not investment advice</span></footer></main>;
}
function CompanySession({dataset,periodIndex}:{dataset:CompanyDataset;periodIndex:number}){
 const opening=useMemo(()=>constructMachine(dataset,periodIndex),[dataset,periodIndex]);const module=sectors[opening.classification.sector],key=fingerprint(dataset,opening.period);
 const [scenarios,setScenarios]=useState<Scenarios>(()=>{try{const saved=JSON.parse(localStorage.getItem(`gcm:v2:${key}`)||'null');if(saved?.baseline===key&&names.every(n=>validateCompanyScenario(saved.scenarios[n],opening)))return saved.scenarios;}catch{}return defaults(opening)});
 const [active,setActive]=useState<Name>('CUSTOM'),[year,setYear]=useState(0),[playing,setPlaying]=useState(false),[motion,setMotion]=useState(true),[compare,setCompare]=useState(false),[inspect,setInspect]=useState<string|null>(null),[review,setReview]=useState(false),[message,setMessage]=useState(''),[trace,setTrace]=useState<string[]>([]);
 const file=useRef<HTMLInputElement>(null),reviewRef=useRef<HTMLDialogElement>(null);const scenario=scenarios[active];
 const computed=useMemo(()=>{try{return {histories:Object.fromEntries(names.map(n=>[n,simulateCompany(opening,scenarios[n])])) as Record<Name,MachineDefinition[]>,error:''}}catch(e){return {histories:Object.fromEntries(names.map(n=>[n,[opening]])) as Record<Name,MachineDefinition[]>,error:e instanceof Error?e.message:String(e)}}},[opening,scenarios]);
 const history=computed.histories[active],shown=history[Math.min(year,history.length-1)],base=computed.histories.BASE[Math.min(year,computed.histories.BASE.length-1)];
 useEffect(()=>{try{localStorage.setItem(`gcm:v2:${key}`,JSON.stringify({baseline:key,scenarios}));}catch{}},[key,scenarios]);
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>setYear(y=>{if(y>=10){setPlaying(false);return 10}return y+1}),900);return()=>clearInterval(id)},[playing]);
 useEffect(()=>{if(review)reviewRef.current?.showModal();else reviewRef.current?.close()},[review]);
 useEffect(()=>{if(!trace.length)return;const id=setTimeout(()=>setTrace([]),9000);return()=>clearTimeout(id)},[trace]);
 function change(id:string,value:number){const target=active==='BASE'?'CUSTOM':active;setScenarios(old=>({...old,[target]:{...old[active],values:{...old[active].values,[id]:value}}}));setActive(target);setPlaying(false);if(scenario.adopted&&year===0)setYear(1);const map:Record<string,string>={growth:'demand',marginChange:'grossProfit',opexGrowth:'opex',capexRatio:'capex',distribution:'cash',cashConversion:'operatingProfit',investmentLag:'capex',investmentResponse:'capex',inventoryDays:'inventory',loanGrowth:'loans',depositGrowth:'deposits',niiChange:'nii',creditCost:'provision',feeGrowth:'fees',taxRate:'netIncome',payout:'netIncome'};setTrace(descendants(opening,map[id]||'revenue'));}
 function adopt(){setScenarios(old=>({...old,[active]:{...old[active],adopted:true},...(!old.BASE.adopted?{BASE:{...suggestedScenario(opening),adopted:true}}:{})}));setReview(false);setYear(1);setMessage('Scenario assumptions adopted. Reported history remains unchanged.');}
 function reset(){setScenarios(old=>({...old,[active]:suggestedScenario(opening)}));setYear(0);setPlaying(false);setTrace([]);setMessage('Returned to the actual reported company.');}
 function shock(){if(!scenario.adopted){setReview(true);return}if(year>=10)return;if(scenario.shocks.length>=20){setMessage('Shock limit reached. Reset to start again.');return}const kind=opening.classification.sector==='banking'?'credit':'demand';const target=active==='BASE'?'CUSTOM':active;setScenarios(old=>({...old,[target]:{...old[active],shocks:[...old[active].shocks,{id:crypto.randomUUID(),year:year+1,kind}]}}));setActive(target);setYear(year+1);setTrace(descendants(opening,kind==='credit'?'provision':'demand'));setMessage(`${kind==='credit'?'Credit provision rate doubled':'Demand level reduced by 20%'} from year ${year+1}.`);}
 function exportScenarios(){const blob=new Blob([JSON.stringify({schemaVersion:2,baseline:key,ticker:dataset.ticker,period:opening.period,scenarios},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${dataset.ticker}-${opening.period}-scenarios.json`;a.click();URL.revokeObjectURL(url)}
 async function importScenarios(e:React.ChangeEvent<HTMLInputElement>){try{const f=e.target.files?.[0];if(!f)return;if(f.size>100000)throw new Error('File too large.');const data=JSON.parse(await f.text());if(data.schemaVersion!==2||data.baseline!==key)throw new Error('The company, historical period or source snapshot differs. Load the matching baseline first.');if(!data.scenarios||!names.every(n=>validateCompanyScenario(data.scenarios[n],opening)))throw new Error('Invalid scenario assumptions.');setScenarios(data.scenarios);setYear(0);setPlaying(false);setMessage('Imported scenarios for this exact reported baseline.');}catch(err){setMessage(err instanceof Error?err.message:String(err))}e.target.value=''}
 const known=shown.nodes.filter(n=>n.value!=null).length;const bank=opening.classification.sector==='banking';const previous=dataset.periods.find(p=>p.fiscalYear===opening.fiscalYear-1);
 const comparisonMetrics=bank?['revenue','nii','provision','netIncome','deposits','loans','equity','cet1']:['revenue','operatingProfit','operatingCashFlow','freeCashFlow','cash','capex',...(opening.classification.sector==='retail'?['inventory','inventoryTurns']:['rd','ppe'])];
 const controls=<div className="company-controls">{module.controls.map(c=><label className="slider-control" key={c.id}><span>{c.label}<output>{scenario.values[c.id].toFixed(c.unit==='years'||c.unit==='days'?0:1)} {c.unit}</output></span><input aria-label={c.label} type="range" min={c.min} max={c.max} step={c.step} value={scenario.values[c.id]} onChange={e=>change(c.id,+e.target.value)} disabled={!scenario.adopted&&!review}/>{review&&<small>{c.explanation}</small>}</label>)}</div>;
 return <>
 <section className="v2-business-bar"><div><span className="status-light"/><strong>{module.label}</strong><span className="data-tag">{shown.year?`${active} · SCENARIO YEAR ${shown.year}`:'ACTUAL COMPANY'}</span></div><button className="text-button" onClick={()=>setInspect('classification')}>Why this machine? <Info size={13}/></button><span>{known}/{shown.nodes.length} components have values</span></section>
 {(message||computed.error)&&<div className="notice" role={computed.error?'alert':'status'}>{computed.error||message}<button onClick={()=>setMessage('')} aria-label="Dismiss message">×</button></div>}
 <div className={`workspace company-workspace ${compare?'compare-mode':''}`}><section className="machine-main">{compare&&<div className="compare-machine-title">{year?`${active} SCENARIO · YEAR ${year}`:'ACTUAL COMPANY'}</div>}<CompanyMachine machine={shown} inspect={setInspect} motion={motion} trace={trace}/></section>
 {compare?<section className="comparison-machine"><div className="compare-machine-title">{year?'BASE SCENARIO / SAME YEAR':'ACTUAL COMPANY / OPENING STATE'}</div><CompanyMachine machine={base} inspect={id=>{setActive('BASE');setInspect(id)}} motion={motion} small/></section>:<aside className="instrument-panel"><h2 className="ribbon">{module.label.toUpperCase()} / GAUGES</h2><div className="gauges">{shown.gauges.map(k=>{const n=getNode(shown,k);const level=n?.value==null?null:n.unit==='ratio'?(k==='revenueGrowth'?(n.value+.5):n.value):n.unit==='multiple'?n.value/15:n.value/Math.max(1,Math.abs(getNode(opening,k)?.value||1)*2);return <Gauge key={k} label={n?.label||k} value={showValue(n)} level={level} onClick={()=>setInspect(k)} negative={n?.value!=null&&n.value<0} detail={`${n?.status} · ${n?.period} · ${n?.source} · ${n?.calculation||n?.reason||'Reported value'} · Gauge scale: ${n?.unit==='USD'?'0–2× opening reported value':k==='revenueGrowth'?'−50% to +50%':n?.unit==='multiple'?'0–15×':'0–100%'}`}/>})}</div><h2 className="ribbon">WHAT CHANGED?</h2><div className="changed-note">{year?<><strong>{showValue(getNode(shown,'revenueGrowth'))} revenue change</strong><p>Versus the prior modeled year. All future values use your adopted assumptions.</p></>:previous?<><strong>{showValue(getNode(shown,'revenueGrowth'))} revenue growth</strong><p>FY{opening.fiscalYear} versus FY{previous.fiscalYear}. Inspect a component to see its source.</p></>:<p>No earlier consecutive annual observation is published.</p>}</div><h2 className="ribbon">EVIDENCE / MODEL BOUNDARY</h2><div className="unknown-summary"><p>{bank?'Future CET1 and liquidity coverage require regulatory inputs. Industrial FCF and ROIC are not applied.':'Customers, retention and competitive advantage are not inferred from financial statements.'}</p><button className="text-button" onClick={()=>setInspect('momentum')}>Inspect momentum coverage <ArrowRight size={12}/></button></div><button className="fork-button" onClick={()=>setReview(true)}>{scenario.adopted?'Review assumptions':'Fork into a scenario'} <ArrowRight size={14}/></button></aside>}
 </div>
 {trace.length>0&&<div className="causal-trace" aria-live="polite"><strong>CAUSAL PATH</strong>{trace.filter(id=>getNode(shown,id)).slice(0,8).map((id,i)=><span key={id}>{i>0&&'→ '}{getNode(shown,id)?.label} <b>{showValue(getNode(shown,id))}</b></span>)}<small>Highlighted links are model relationships. Investment effects follow the adopted lag.</small></div>}
 <section className="scenario-controls"><div className="controls-heading"><h2>{scenario.adopted?'ADOPTED SCENARIO ASSUMPTIONS':'SCENARIO CONSOLE / ASSUMPTIONS REQUIRED'}</h2><button className="text-button" onClick={()=>setReview(true)}>{scenario.adopted?'Review all assumptions':'Review & adopt assumptions'} <ArrowRight size={13}/></button></div>{controls}</section>
 <section className="transport"><div className="playback"><button className="primary-button" disabled={!!computed.error} onClick={()=>{if(!scenario.adopted){setReview(true);return}if(year===10)setYear(0);setPlaying(v=>!v)}}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'Pause':'Play'}</button><button aria-label="Step forward" disabled={!scenario.adopted||year===10||!!computed.error} onClick={()=>{setPlaying(false);setYear(y=>y+1)}}><SkipForward size={15}/></button><button onClick={reset}><RotateCcw size={14}/>Reset</button><button onClick={()=>{if(!scenario.adopted){setReview(true);return}setYear(0);setPlaying(true)}} disabled={!!computed.error}>Run 10 years</button></div><label className="timeline"><span>{year===0?'ACTUAL':`YEAR ${year}`}<span>10 YEARS →</span></span><input aria-label="Forecast year" type="range" min="0" max="10" value={year} disabled={!scenario.adopted||!!computed.error} onChange={e=>{setPlaying(false);setYear(+e.target.value)}}/></label><div className="scenario-tabs" aria-label="Scenario containers">{names.map(n=><button key={n} aria-pressed={active===n} onClick={()=>{setActive(n);setPlaying(false);if(!scenarios[n].adopted)setYear(0)}}>{n}</button>)}</div><button aria-label="Compare machines" aria-pressed={compare} onClick={()=>setCompare(v=>!v)}><Columns2 size={16}/></button></section>
 <section className="workbench"><div className="shock-controls"><button onClick={shock} disabled={year===10}><Zap size={14}/>{bank?'Credit losses ×2':'Demand −20%'}</button><span>{scenario.shocks.length?`${scenario.shocks.length} active shock${scenario.shocks.length>1?'s':''}`:'Shocks take effect in the next year'}</span></div><div className="file-controls"><button onClick={()=>setMotion(v=>!v)}>{motion?'Reduce motion':'Restore motion'}</button><button onClick={exportScenarios}><Download size={14}/>Export</button><button onClick={()=>file.current?.click()}><Upload size={14}/>Import</button><input type="file" accept="application/json,.json" ref={file} hidden onChange={importScenarios}/></div></section>
 <details className="comparison-table"><summary>Compare scenario outputs · {year===0?'opening reported state':`year ${year}`}</summary><div className="table-scroll"><table><thead><tr><th>Measure</th>{names.map(n=><th key={n}>{n}{scenarios[n].adopted?'':' / NOT ADOPTED'}</th>)}</tr></thead><tbody>{comparisonMetrics.map(id=><tr key={id}><th>{getNode(opening,id)?.label||id}</th>{names.map(n=><td key={n}>{year>0&&!scenarios[n].adopted?'—':showValue(getNode(computed.histories[n][Math.min(year,computed.histories[n].length-1)],id))}</td>)}</tr>)}</tbody></table></div><p>BULL and BEAR contain no prescribed optimism or pessimism. Future BASE is a scenario, not reported fact.</p></details>
 <details className="comparison-table"><summary>Inspect all machine components, including missing data</summary><div className="component-index">{shown.nodes.map(n=><button key={n.id} onClick={()=>setInspect(n.id)}>{n.label}<small>{showValue(n)} · {n.status}</small></button>)}</div></details>
 <p className="source-note">Published snapshot: {dataset.provider} · retrieved {dataset.retrieved} · report date {opening.period}. This release provides {dataset.periods.length} annual periods; no live data or TTM inference.</p>
 <dialog ref={reviewRef} className="assumption-dialog" onCancel={()=>setReview(false)}><header><div><span className="eyebrow">FORK {dataset.ticker} / {opening.period}</span><h2>Make the assumptions explicit</h2></div><button onClick={()=>setReview(false)} aria-label="Close assumption review">×</button></header><p>These are suggested scenario inputs, not company disclosures. Adopting them enables a limited {module.label.toLowerCase()} simulation. Unknown customer and regulatory metrics remain unknown.</p>{controls}<ul>{module.limitations.map(t=><li key={t}>{t}</li>)}</ul><footer><button onClick={()=>setReview(false)}>Cancel</button><button className="primary-button" onClick={adopt}>Adopt assumptions & fork</button></footer></dialog>
 {inspect&&<CompanyInspector machine={shown} nodeId={inspect} close={()=>setInspect(null)}/>}
 </>;
}
