import { useId, useEffect, useRef, useState, type CSSProperties } from 'react';
import { getNode } from '../translation/construct';
import type { MachineDefinition } from '../ontology/types';
import { showDelta, showValue } from '../format';
import type { Change } from '../simulation/explain';
export {showValue};
const toothPath=Array.from({length:72},(_,i)=>{const a=i*Math.PI/36,r=i%4<2?47:41;return `${i?'L':'M'}${Math.cos(a)*r},${Math.sin(a)*r}`}).join(' ')+'Z';
const wrap=(text:string)=>{const words=text.toUpperCase().split(' ');const result:string[]=[];for(const w of words){if(result.length&&result[result.length-1].length+w.length<16)result[result.length-1]+=' '+w;else result.push(w)}return result};
// A delta badge shows how far a component moved from BASE this year; `pulse` restarts the propagation highlight.
function Delta({c,x=0,y=0}:{c?:Change;x?:number;y?:number}){if(!c)return null;const text=showDelta(c.delta,c.unit);return <g transform={`translate(${x} ${y})`} className={`delta-badge ${c.delta<0?'down':'up'}`}><rect x={-text.length*3.4-5} y="-9" width={text.length*6.8+10} height="15" rx="7"/><text textAnchor="middle" y="2">{text}</text></g>}
// Concepts in the universal loop that no filing measures. They are drawn as ghosts, never as working parts.
const unmeasured=new Set(['demand','customers','capacity','customerValue','advantage','traffic']);
export default function CompanyMachine({machine:m,opening=m,inspect,motion,trace=[],deltas={},pulse=0,small=false}:{machine:MachineDefinition;opening?:MachineDefinition;inspect:(id:string)=>void;motion:boolean;trace?:string[];deltas?:Record<string,Change>;pulse?:number;small?:boolean}){
 const id=useId().replace(/:/g,'');const f=(key:string)=>`url(#${id}-${key})`;const [zoom,setZoom]=useState(1);const wheel=useRef<SVGGElement>(null);const gears=useRef<(SVGGElement|null)[]>([]);const angle=useRef(0);const speed=useRef(0);
 const bank=m.classification.sector==='banking',retail=m.classification.sector==='retail',general=m.classification.sector==='general';
 const fundingGap=getNode(m,'fundingGap')?.value||0,fcf=getNode(m,'freeCashFlow')?.value;
 // Every speed and level is this year's value relative to the reported opening value, capped at 3×.
 const rel=(key:string)=>{const v=getNode(m,key)?.value,v0=getNode(opening,key)?.value;return v==null||!v0?null:Math.max(-3,Math.min(3,v/Math.abs(v0)))};
 const outKey=bank?'netIncome':'operatingCashFlow',out=getNode(m,outKey);
 const state=m.year===0?`REPORTED FY${m.fiscalYear}`:fundingGap>0?'UNFUNDED CASH GAP':bank?((out?.value??0)<0?'LOSS-MAKING':'RUNNING'):((fcf??0)<0?'BURNING CASH':'RUNNING');
 const rpm=10*Math.max(0,rel(outKey)??0);
 const measured=m.stages.filter(k=>!(unmeasured.has(k)&&getNode(m,k)?.value==null)),ghosts=m.stages.filter(k=>!measured.includes(k));
 const firstIdx=m.stages.indexOf(measured[0]),ghostOrder=[...ghosts.filter(k=>m.stages.indexOf(k)>firstIdx),...ghosts.filter(k=>m.stages.indexOf(k)<firstIdx)];
 // Working parts sweep over the top of the ring; ghosts sit on an outer arc underneath.
 const ring=measured.map((key,i)=>{const a=(160+i*220/Math.max(1,measured.length-1))*Math.PI/180;return {key,x:468+218*Math.cos(a),y:299+218*Math.sin(a)}});
 const ghostRing=ghostOrder.map((key,i)=>{const a=(ghostOrder.length===1?90:55+i*70/(ghostOrder.length-1))*Math.PI/180;return {key,x:468+262*Math.cos(a),y:299+262*Math.sin(a)}});
 const gearSpeed=ring.map(({key})=>10*(rel(key)??0));
 useEffect(()=>{if(!motion||matchMedia('(prefers-reduced-motion: reduce)').matches)return;let frame=0,last=0,ga=0;const animate=(now:number)=>{const dt=last?Math.min(.1,(now-last)/1000):0;last=now;speed.current+=(rpm-speed.current)*Math.min(1,dt*2);angle.current=(angle.current+speed.current*6*dt)%360;ga+=6*dt;wheel.current?.setAttribute('transform',`rotate(${angle.current} 468 299)`);gears.current.forEach((g,i)=>g?.setAttribute('transform',`rotate(${(ga*gearSpeed[i]*(i%2?-1:1))%360})`));frame=requestAnimationFrame(animate)};frame=requestAnimationFrame(animate);return()=>cancelAnimationFrame(frame)},[rpm,gearSpeed.join(),motion]);
 const hit=(key:string)=>({role:'button',tabIndex:0,'aria-label':`Inspect ${getNode(m,key)?.label||key}`,onClick:()=>inspect(key),onKeyDown:(e:React.KeyboardEvent)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();inspect(key)}}});
 const tankKey=bank?'deposits':'cash',tank=getNode(m,tankKey),tank0=getNode(opening,tankKey)?.value,fill=tank?.value==null||!tank0?0:Math.max(0,Math.min(1,tank.value/(2*tank0)));
 const capKey=bank?'cet1':'capital',capNode=getNode(m,capKey),cap0=getNode(opening,capKey)?.value,capFill=capNode?.value==null?null:Math.max(0,Math.min(1,capNode.value/(bank?.25:2*(cap0||1))));
 const fy=`FY${String(opening.fiscalYear).slice(2)}`;
 const moduleKeys=m.moduleNodes.slice(0,3);
 return <div className={`company-drawing ${small?'small-machine':''} ${motion?'':'motion-paused'}`} style={{'--flow-time':`${Math.max(.6,4/Math.max(.25,rpm/10))}s`} as CSSProperties}>
  <div className="machine-tools"><span>PLATE {bank?'03':retail?'02':general?'00':'01'} / {m.classification.label.toUpperCase()}</span><div><button aria-label="Zoom out" onClick={()=>setZoom(Math.max(1,zoom-.25))}>−</button><button onClick={()=>setZoom(1)}>{Math.round(zoom*100)}%</button><button aria-label="Zoom in" onClick={()=>setZoom(Math.min(2,zoom+.25))}>+</button></div></div>
  <div className="machine-pan"><svg className="machine company-svg" viewBox="0 0 1070 670" style={{width:`${zoom*100}%`}} role="group" aria-label={`${m.ticker} ${m.classification.label} economic machine`}>
  <defs><linearGradient id={`${id}-metal`} x2="1" y2="1"><stop stopColor="#e9e7d9"/><stop offset=".2" stopColor="#7d8674"/><stop offset=".4" stopColor="#dedfcd"/><stop offset=".51" stopColor="#f9f3df"/><stop offset=".65" stopColor="#9ba58d"/><stop offset="1" stopColor="#d2d5be"/></linearGradient><linearGradient id={`${id}-brass`}><stop stopColor="#584020"/><stop offset=".25" stopColor="#b68b34"/><stop offset=".5" stopColor="#f9dc8a"/><stop offset=".73" stopColor="#b58938"/><stop offset="1" stopColor="#584020"/></linearGradient><linearGradient id={`${id}-dark`}><stop stopColor="#29382a"/><stop offset=".35" stopColor="#8b947f"/><stop offset=".58" stopColor="#34482e"/><stop offset="1" stopColor="#a6ad90"/></linearGradient><radialGradient id={`${id}-face`}><stop stopColor="#fff8e7"/><stop offset=".85" stopColor="#e4dfcb"/><stop offset="1" stopColor="#b0b399"/></radialGradient><linearGradient id={`${id}-glass`}><stop stopColor="#435439" stopOpacity=".4"/><stop offset=".3" stopColor="#fffde0" stopOpacity=".1"/><stop offset=".46" stopColor="#fffde8" stopOpacity=".7"/><stop offset=".8" stopColor="#fffde0" stopOpacity=".1"/><stop offset="1" stopColor="#435439" stopOpacity=".4"/></linearGradient><filter id={`${id}-shadow`} x="-30%" y="-30%" width="160%" height="160%"><feDropShadow dx="2" dy="3" stdDeviation="2" floodColor="#24311f" floodOpacity=".38"/></filter><pattern id={`${id}-hatch`} width="5" height="5" patternTransform="rotate(45)" patternUnits="userSpaceOnUse"><path d="M0 0V5" stroke="#8a9474" strokeWidth="1"/></pattern></defs>
  <g fill="none" strokeLinejoin="round"><path d="M113 121H170Q195 121 195 146V254H251M116 368H186V460H285M649 441H784V328H946V205H693M780 157V75H979V217" stroke="#414d36" strokeWidth="17"/><path d="M113 121H170Q195 121 195 146V254H251M116 368H186V460H285M649 441H784V328H946V205H693M780 157V75H979V217" stroke={f('brass')} strokeWidth="12"/><path className="cash-stream" d="M113 121H170Q195 121 195 146V254H251M649 441H784V328H946V205H693" style={{animationPlayState:motion?'running':'paused'}}/></g>
  {[[195,181],[186,405],[784,380],[946,267],[979,147]].map(([x,y])=><g key={x} transform={`translate(${x} ${y})`}><rect x="-11" y="-7" width="22" height="14" rx="2" fill={f('metal')} stroke="#445536"/><path d="M-7-7V7M7-7V7" stroke="#4a583d"/></g>)}
  <circle cx="468" cy="299" r="245" fill="#9da78a10" stroke="#adb09a"/><circle cx="468" cy="299" r="173" fill="none" stroke="#28463a" strokeWidth="15"/><circle cx="468" cy="299" r="173" fill="none" stroke="#649290" strokeWidth="5" strokeDasharray="38 9"/>
  <g filter={f('shadow')} className={fundingGap>0?'stressed-rotor':''}><circle cx="468" cy="299" r="149" fill={f('metal')} stroke="#434f38" strokeWidth="3"/><circle cx="468" cy="299" r="137" fill={f('dark')} stroke="#eeebd6" strokeWidth="3"/>
  <g ref={wheel}><circle cx="468" cy="299" r="125" fill={f('metal')}/>{Array.from({length:8},(_,i)=><path key={i} d="M457 176L462 236H474L479 176Z" transform={`rotate(${i*45} 468 299)`} fill={f('dark')} stroke="#bcc3a5"/>)}{[86,94,100,106,115,124].map((r,i)=><circle key={r} cx="468" cy="299" r={r} fill="none" stroke={i%2?'#eeead4':'#657457'} />)}</g>
  <g {...hit(outKey)} className="machine-hit"><circle cx="468" cy="299" r="72" fill={f('face')} stroke="#687557" strokeWidth="3"/><text x="468" y="266" textAnchor="middle" className="small-label">{bank?'NET INCOME':'OPERATING CASH FLOW'}</text><text x="468" y="303" textAnchor="middle" className="momentum-value">{showValue(out)}</text><text x="468" y="324" textAnchor="middle" className="small-label">{m.ticker} / {m.year?`SCENARIO Y${m.year}`:`FY${m.fiscalYear}`}</text><text x="468" y="339" textAnchor="middle" className="small-label">WHEEL SPEED = VS {fy}</text><Delta c={deltas[outKey]} x={468} y={357}/></g></g>
  {ring.map(({key,x,y},i)=>{const n=getNode(m,key)!;return <g key={`${key}-${trace.includes(key)?pulse:0}`} {...hit(key)} transform={`translate(${x} ${y})`} className={`machine-hit sector-gear ${trace.includes(key)?'causal-highlight':''} ${n.value==null?'unknown-node':''}`} style={{animationDelay:`${trace.indexOf(key)*.35}s`}}><title>{n.label}: {showValue(n)} · {n.status} · {n.period}</title><g filter={f('shadow')}><g ref={el=>{gears.current[i]=n.value==null?null:el}}><path d={toothPath} fill={f('metal')} stroke="#46533a" strokeWidth="2"/></g><circle r="35" fill={f('face')} stroke="#8e967a" strokeWidth="2"/></g>{wrap(n.label).slice(0,2).map((line,j)=><text key={j} textAnchor="middle" y={-9+j*11} className="gear-label">{line}</text>)}<text y="20" textAnchor="middle" className={`gear-number ${n.value==null?'unknown-label':''}`}>{showValue(n)}</text><Delta c={deltas[key]} y={50}/></g>})}
  {ghostRing.length>0&&<g className="ghost-ring"><path d={`M${468+262*Math.cos(30*Math.PI/180)} ${299+262*Math.sin(30*Math.PI/180)} A262 262 0 0 1 ${468+262*Math.cos(150*Math.PI/180)} ${299+262*Math.sin(150*Math.PI/180)}`} fill="none" stroke="#9aa08a" strokeWidth="1.5" strokeDasharray="4 6"/>{ghostRing.map(({key,x,y})=>{const n=getNode(m,key)!;return <g key={key} {...hit(key)} transform={`translate(${x} ${y})`} className="machine-hit ghost-part"><title>{n.label}: not measured by any filing</title><circle r="26" fill="#f4f1e466" stroke="#9aa08a" strokeWidth="1.5" strokeDasharray="3 4"/>{wrap(n.label).slice(0,2).map((line,j)=><text key={j} textAnchor="middle" y={-3+j*10} className="ghost-label">{line}</text>)}</g>})}<text x="468" y="608" textAnchor="middle" className="ghost-caption">NOT MEASURED · THE LOOP THAT RENEWS DEMAND IS DRAWN, NOT SIMULATED</text></g>}
  <g transform="translate(18 32)"><rect width="185" height="25" className="blue-plate"/><text x="92" y="17" textAnchor="middle" className="white-label">{bank?'DEPOSITS → CREDIT':retail?'INVENTORY → SALES':general?'ASSETS → OUTPUT':'SOFTWARE → CLOUD'}</text>
  {moduleKeys.map((key,i)=>{const live=getNode(m,key)!,reportedOnly=m.year>0&&live.value==null&&getNode(opening,key)?.value!=null,n=reportedOnly?getNode(opening,key)!:live;return <g key={key} {...hit(key)} className="machine-hit" transform={`translate(9 ${44+i*142})`}>
   {bank?<><rect x="6" width="148" height="65" rx="19" fill={f('glass')} stroke="#687b52" strokeWidth="3"/><rect x="10" y="23" width="140" height="35" rx="9" fill="#7b9b7e" opacity=".5"/><ellipse cx="80" cy="5" rx="73" ry="9" fill={f('metal')} stroke="#5a6a46"/><ellipse cx="80" cy="64" rx="73" ry="9" fill={f('metal')} stroke="#5a6a46"/></>:retail?<><rect width="161" height="64" fill={f('metal')} stroke="#586c43" strokeWidth="2"/>{Array.from({length:8},(_,j)=><rect key={j} x={9+j%4*38} y={9+Math.floor(j/4)*25} width="28" height="19" fill={f('face')} stroke="#88936e"/>)}<path d="M0 34H161M0 63H161" stroke="#435832" strokeWidth="4"/></>:<><rect width="161" height="69" rx="3" fill={f('dark')} stroke="#435638" strokeWidth="2"/>{[0,1,2].map(j=><g key={j}><rect x="7" y={7+j*20} width="147" height="15" rx="2" fill={f('metal')}/><circle cx="18" cy={14+j*20} r="2" fill="#82a856"/><path d={`M80 ${14+j*20}H145`} stroke="#3c4d31" strokeWidth="3"/></g>)}</>}
   <rect x="0" y="78" width="161" height="43" fill={f('face')} stroke="#899875"/><text x="80" y="93" textAnchor="middle" className="small-label">{n.label.toUpperCase()}</text><text x="80" y="112" textAnchor="middle" className={`module-value ${reportedOnly?'reported-only':''}`}>{showValue(n)}</text>{reportedOnly&&<text x="80" y="134" textAnchor="middle" className="small-label">{fy} REPORTED · NOT PROJECTED</text>}<Delta c={deltas[key]} x={80} y={133}/>
  </g>})}<text x="92" y="503" textAnchor="middle" className="small-label">{bank?'FUNDING ≠ REVENUE':retail?'CASH TIED UP IN STOCK':general?'NO SECTOR MODULE YET':'INFRASTRUCTURE + IP'}</text></g>
  <g transform="translate(752 102)" {...hit(bank?'netIncome':'operatingCashFlow')} className="machine-hit"><g filter={f('shadow')}><ellipse cx="59" cy="0" rx="66" ry="14" fill={f('metal')} stroke="#4e5e3f" strokeWidth="3"/><rect width="118" height="190" fill={f('metal')} stroke="#4e5e3f" strokeWidth="3"/><path d="M-5 5V185M124 5V185" stroke={f('brass')} strokeWidth="8"/><rect x="10" y="10" width="98" height="164" fill={f('face')} stroke="#8d9479"/><ellipse cx="59" cy="189" rx="66" ry="12" fill={f('metal')} stroke="#4e5e3f" strokeWidth="3"/></g><text x="59" y="37" textAnchor="middle" className="engine-label">{bank?'BANKING':'ECONOMIC'}</text><text x="59" y="54" textAnchor="middle" className="engine-label">CONVERSION</text><text x="59" y="71" textAnchor="middle" className="engine-label">ENGINE</text>{(bank?['Net interest income','+ Other revenue','− Credit provisions','− Costs / tax']:['Reported revenue','− Cost to deliver','− Operating costs','→ Cash conversion']).map((line,i)=><text key={line} x="59" y={97+i*18} textAnchor="middle" className="small-label">{line}</text>)}<text x="59" y="225" textAnchor="middle" className="metric-value">{showValue(getNode(m,bank?'netIncome':'freeCashFlow'))}</text><text x="59" y="241" textAnchor="middle" className="small-label">{bank?'NET INCOME':'FREE CASH FLOW'}</text><Delta c={deltas[bank?'netIncome':'freeCashFlow']} x={59} y={260}/></g>
  <g transform="translate(935 248)" {...hit(bank?'deposits':'cash')} className="machine-hit"><g filter={f('shadow')}><rect x="-8" y="-7" width="87" height="158" rx="16" fill={f('dark')} stroke="#44573b"/><rect width="71" height="136" fill="#f4ecd5"/><rect x="3" y={132-fill*126} width="65" height={fill*126} fill={bank?'#73948a':'#c09336'}/><rect width="71" height="136" fill={f('glass')}/><path d="M2 2V136M69 2V136" stroke={f('metal')} strokeWidth="5"/><ellipse cx="35" cy="2" rx="39" ry="8" fill={f('metal')} stroke="#4e6140"/><ellipse cx="35" cy="138" rx="39" ry="8" fill={f('metal')} stroke="#4e6140"/></g><rect x="-15" y="164" width="102" height="53" fill={f('face')} stroke="#849071"/><text x="36" y="16" textAnchor="middle" className="small-label">FULL = 2× {fy}</text><text x="36" y="182" textAnchor="middle" className="small-label">{bank?'DEPOSIT FUNDING':'CASH RESERVE'}</text><text x="36" y="204" textAnchor="middle" className="metric-value">{showValue(tank)}</text><Delta c={deltas[bank?'deposits':'cash']} x={36} y={232}/></g>
  <g transform="translate(754 406)" {...hit(bank?'cet1':'capital')} className="machine-hit"><rect width="120" height="83" rx="3" fill={f('metal')} stroke="#526444" strokeWidth="3"/><rect x="12" y="11" width="25" height="62" fill="#35482e"/>{Array.from({length:6},(_,i)=><rect key={i} x="16" y={16+i*9} width="17" height="6" fill={capFill==null?'#737965':i>=6-capFill*6?'#8cb35e':'#556547'}/>)}<text x="78" y="27" textAnchor="middle" className="small-label">{bank?'CET1 RATIO':'LIQUID'}</text><text x="78" y="42" textAnchor="middle" className="small-label">{bank?'REGULATORY':'CAPITAL'}</text><text x="78" y="63" textAnchor="middle" className="module-value">{showValue(capNode)}</text><text x="78" y="77" textAnchor="middle" className="small-label">{bank?'FULL = 25%':`FULL = 2× ${fy}`}</text>{!bank&&<Delta c={deltas.capital} x={60} y={100}/>}</g>
  <g transform="translate(357 378)"><rect width="222" height="30" rx="3" fill={f('face')} stroke="#82916c"/><text x="111" y="20" textAnchor="middle" className={`status-label ${fundingGap>0?'negative':''}`}>{state}</text></g>
  </svg></div>
  <div className="machine-key"><span><i className="gold-dot"/> Cash / value flows</span><span><i className="hollow-dot"/> UNKNOWN = missing evidence</span><span><i className="ghost-dot"/> Ghost = concept no filing measures</span><span>Speeds and levels = value vs {fy}</span><span>Click any component to inspect</span></div>
 </div>;
}
