import {useEffect,useRef} from 'react';
import {X,ExternalLink} from 'lucide-react';
import type {MachineDefinition} from '../ontology/types';
import {getNode} from '../translation/construct';
import {showValue} from '../format';
import {equationFor,refKind} from '../simulation/equations';
import {refLabel,findChange,type Experiment} from '../simulation/explain';
import {ChangeDetail} from './Demonstration';
export default function CompanyInspector({machine:m,nodeId,close,experiment:x,year=0,inspect}:{machine:MachineDefinition;nodeId:string;close:()=>void;experiment?:Experiment|null;year?:number;inspect?:(id:string)=>void}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close()},[]);
 const n=getNode(m,nodeId);const upstream=m.edges.filter(e=>e.to===nodeId),downstream=m.edges.filter(e=>e.from===nodeId);
 const eq=equationFor(m,nodeId),change=x&&year?findChange(x,nodeId,year):undefined,absorbed=x&&year?x.absorbed.find(a=>a.node===nodeId&&a.year===year):undefined;
 const tag=(kind:string)=>kind==='hypothesis'?'MODEL HYPOTHESIS':kind==='concept'?'CONCEPTUAL LINK · NOT SIMULATED':'ACCOUNTING RELATION';
 return <dialog ref={ref} className="inspector" onCancel={close} onClick={e=>{if(e.target===ref.current)close()}}><div className="inspector-inner"><header><span className="eyebrow">{m.ticker} / COMPONENT INSPECTOR</span><button onClick={close} aria-label="Close inspector"><X size={18}/></button></header>
 {nodeId==='classification'?<><h2>Why this machine?</h2><h3>{m.classification.label}</h3><p>{m.classification.rationale}</p><a href={m.classification.evidence} target="_blank" rel="noreferrer">Classification evidence <ExternalLink size={12}/></a><p>{m.classification.coverage}</p></>:<><h2>{n?.label||'Business momentum'}</h2><div className="inspection-value">{showValue(n)}</div><span className="data-tag">{n?.status||'UNKNOWN'}</span><p>{n?.meaning}</p><dl><dt>Period</dt><dd>{n?.period||m.period}</dd><dt>Source / confidence</dt><dd>{n?.url?<a href={n.url} target="_blank" rel="noreferrer">{n.source} <ExternalLink size={12}/></a>:n?.source||'No complete evidence'}</dd><dt>Calculation / missing evidence</dt><dd>{n?.calculation||n?.reason||'Direct observation from the source statement.'}</dd></dl>
 {nodeId==='momentum'&&<><h3>Why is the flywheel changing speed?</h3>{m.momentum.value==null?<p>{m.momentum.reason}</p>:<><p>This is a narrow scenario indicator, not the full-business composite or an investment score.</p>{m.momentum.parts.map(p=><div className="contribution" key={p.label}><div><span>{p.label}</span><strong className={p.contribution>=0?'positive':'negative'}>{p.contribution>0?'+':''}{p.contribution.toFixed(2)}</strong></div><small>{p.formula}</small></div>)}</>}</>}
 {x&&year>0&&<><h3>Why did this change? · year {year} vs BASE</h3>{change?<><div className="inspection-value small">{showValue({value:change.base,unit:change.unit})} → {showValue({value:change.scen,unit:change.unit})}</div><ChangeDetail x={x} c={change} inspect={id=>inspect?.(id)}/></>:<p>{absorbed?absorbed.reason:'Unchanged: none of its equation inputs differ from BASE in this year.'}</p>}</>}
 {eq&&<><h3>Forecast equation</h3><p className="change-equation"><b>{n?.label}</b> = {eq.formula}</p><small className="data-tag">{tag(eq.kind)}</small><p>Levers: {eq.inputs.filter(r=>refKind(r)==='assume'||refKind(r)==='shock').map(r=>refLabel(r,m.classification.sector)).join(', ')||'none — pure accounting identity'}. Reported anchors: {eq.inputs.filter(r=>refKind(r)==='opening').map(r=>refLabel(r,m.classification.sector)).join(', ')||'none'}.</p></>}
 <h3>What feeds this component?</h3>{upstream.length?upstream.map(e=><div className="edge-detail" key={e.id}><strong>{getNode(m,e.from)?.label||e.from}</strong><p>{e.formula}</p><small>{tag(e.kind)} · {e.lag?`${e.lag}-year lag`:'Same period'}</small></div>):<p>No upstream accounting identity. This is an observation, assumption or unmeasured concept.</p>}
 <h3>What does it affect?</h3>{downstream.length?downstream.map(e=><div className="edge-detail" key={e.id}><strong>{getNode(m,e.to)?.label||e.to}</strong><p>{e.formula}</p><small>{tag(e.kind)} · {e.lag?`${e.lag}-year lag`:'Same period'}</small></div>):<p>No outgoing equation in this release.</p>}</>}
 <details><summary>Model scope and limitations</summary>{m.limitations.map(t=><p key={t}>{t}</p>)}</details></div></dialog>;
}
