import {ArrowRight,ExternalLink,Play,RotateCcw} from 'lucide-react';
import type {MachineDefinition,SectorModule} from '../ontology/types';
import {getNode} from '../translation/construct';
import {controlsFor} from '../sectors';
import {equationsFor} from '../simulation/equations';
import {HORIZON,suggestedBasis} from '../simulation/company';
import type {Demonstration as Demo} from '../simulation/demos';
import {describeLever,isLeverRef,rootPath,type Change,type Experiment} from '../simulation/explain';
import {showDelta,showValue} from '../format';
export const steps=['Reported data','Economic machine','Causal model','Pull one lever','Propagation','Five years','Explain every change'] as const;
export function ChangeDetail({x,c,inspect}:{x:Experiment;c:Change;inspect:(id:string)=>void}){
 const scale=Math.max(...c.contributions.map(p=>Math.abs(p.effect)),Math.abs(c.interaction),1e-12);
 return <div className="change-detail"><p className="change-equation"><b>{c.label}</b> = {c.formula}</p>
  {c.contributions.map(p=>{const l=x.levers.find(v=>v.ref===p.ref);return <div className="contribution-row" key={p.ref}><button className="text-button" disabled={!p.source} onClick={()=>p.source&&inspect(p.source.node)}>{p.label}{l?' · LEVER':''}</button><span>{l?describeLever(l).split(': ')[1]:isLeverRef(p.ref)?`×${+p.base.toFixed(3)} → ×${+p.scen.toFixed(3)}`:showDelta(p.scen-p.base,p.unit)}</span><i className={p.effect<0?'negative':'positive'} style={{width:`${Math.abs(p.effect)/scale*100}%`}}/><strong>{showDelta(p.effect,c.unit)}</strong></div>})}
  {c.interaction!==0&&<div className="contribution-row"><span>Interaction (non-additive)</span><span/><i style={{width:`${Math.abs(c.interaction)/scale*100}%`}}/><strong>{showDelta(c.interaction,c.unit)}</strong></div>}
  <p className="root-path"><span>ROOT CAUSE</span>{rootPath(x,c).map((s,i)=><span key={i}>{i>0&&' ← '}{'node' in s?`${s.label} Y${s.year} ${showDelta(s.delta,s.unit)}`:<b>{s.label}{isLeverRef(s.ref)?' (lever)':''}</b>}</span>)}</p></div>;
}
export default function Demonstration({open=true,setOpen=()=>{},opening,module,demo,x,year,step,setStep,applyDemo,run,replay,inspect,setYear}:{open?:boolean;setOpen?:(v:boolean)=>void;opening:MachineDefinition;module:SectorModule;demo?:Demo;x:Experiment|null;year:number;step:number;setStep:(n:number)=>void;applyDemo:()=>void;run:()=>void;replay:()=>void;inspect:(id:string)=>void;setYear:(n:number)=>void}){
 const shownYear=year||1,basis=suggestedBasis(opening),eqs=equationsFor(opening),reported=opening.nodes.filter(n=>(n.status==='OBSERVED'||n.status==='ESTIMATED'||(n.status==='CALCULATED'&&n.inputs))&&!(n.id==='capital'&&opening.classification.sector!=='banking'));
 const needLever=<p className="demo-hint">Pull the lever first (step 4). Explanations compare your scenario with BASE, which shares every other assumption.</p>;
 const yearChips=<div className="year-chips" role="group" aria-label="Explained year">{Array.from({length:HORIZON},(_,i)=><button key={i} aria-pressed={shownYear===i+1} onClick={()=>setYear(i+1)}>Y{i+1}</button>)}</div>;
 const body=[
  <><p>Every value below comes from the published FY{opening.fiscalYear} snapshot. CALCULATED rows state their accounting identity; nothing is estimated.</p><div className="demo-table"><table><thead><tr><th>Component</th><th>Value</th><th>Status</th><th>Source</th></tr></thead><tbody>{reported.map(n=><tr key={n.id}><th><button className="text-button" onClick={()=>inspect(n.id)}>{n.label}</button></th><td>{showValue(n)}</td><td>{n.status}</td><td>{n.url?<a href={n.url} target="_blank" rel="noreferrer" aria-label={`Source: ${n.calculation||n.source}`}><span className="src-text">{n.calculation||n.source}</span> <ExternalLink size={10}/></a>:n.calculation||n.source}</td></tr>)}</tbody></table></div></>,
  <><p><b>{module.label}.</b> {opening.classification.rationale}</p><p>The ring is the universal economic core; the left-hand module is this sector’s machinery. {opening.nodes.filter(n=>n.value!=null).length} of {opening.nodes.length} components have values. These stay UNKNOWN rather than being invented:</p><div className="chip-list">{opening.nodes.filter(n=>n.value==null).map(n=><button key={n.id} onClick={()=>inspect(n.id)}>{n.label}</button>)}</div><button className="text-button" onClick={()=>inspect('classification')}>Why this machine? <ArrowRight size={12}/></button></>,
  <><p>The simulator evaluates these equations in order each year. The machine’s computed links are generated from their inputs, so what you inspect is what runs.</p><ol className="equation-list">{eqs.map(e=><li key={e.target}><button className="text-button" onClick={()=>inspect(e.target)}>{getNode(opening,e.target)?.label||e.target}</button> = {e.formula}<small>{e.kind==='hypothesis'?'MODEL HYPOTHESIS':'ACCOUNTING'}</small></li>)}</ol><p className="demo-hint">Conceptual links such as {opening.edges.filter(e=>e.kind==='concept').slice(0,2).map(e=>`${getNode(opening,e.from)?.label} → ${getNode(opening,e.to)?.label}`).join(' and ')} are drawn but never simulated.</p></>,
  demo?<><p className="demo-question">{demo.question}</p><p>{demo.why}</p><button className="primary-button" onClick={applyDemo}>Pull lever: {module.controls.find(c=>c.id===demo.lever)?.label} +{demo.delta}{module.controls.find(c=>c.id===demo.lever)?.unit==='days'?' days':'pp'} <ArrowRight size={13}/></button><p className="demo-hint">BASE and your scenario share every other assumption:</p><ul className="basis-list">{controlsFor(opening).map(c=><li key={c.id} className={c.id===demo.lever?'is-lever':''}><span>{c.label}</span><b>{basis[c.id]||'Neutral placeholder — not a company disclosure'}</b></li>)}</ul></>:<p>No canonical lever is defined for this company.</p>,
  x?<><p>Year {year||1}: {x.levers.map(describeLever).join('; ')} moves these components, in the order the equations run.</p><ol className="propagation-list">{x.changes.filter(c=>c.year===(year||1)).map(c=><li key={c.node}><button className="text-button" onClick={()=>inspect(c.node)}>{c.label}</button> <b className={c.delta<0?'negative':'positive'}>{showDelta(c.delta,c.unit)}</b><small>via {c.contributions.map(p=>p.label).join(', ')}</small></li>)}</ol>{x.absorbed.filter(a=>a.year===(year||1)).map(a=><p className="demo-hint" key={a.node}><b>{a.label} unchanged.</b> {a.reason}</p>)}<button onClick={replay}><RotateCcw size={13}/> Replay propagation</button></>:needLever,
  x&&demo?<><div className="demo-actions"><button className="primary-button" onClick={run}><Play size={13}/> Run five years</button>{yearChips}</div><div className="demo-table"><table><thead><tr><th>Your scenario vs BASE</th>{Array.from({length:HORIZON},(_,i)=><th key={i} className={`yr ${shownYear===i+1?'current':''}`}>Y{i+1}</th>)}</tr></thead><tbody>{demo.watch.map(id=><tr key={id}><th><button className="text-button" onClick={()=>inspect(id)}>{getNode(opening,id)?.label}</button></th>{Array.from({length:HORIZON},(_,i)=>{const s=getNode(x.scen[i+1],id),b=getNode(x.base[i+1],id),c=x.changes.find(c=>c.node===id&&c.year===i+1);return <td key={i} className={`yr ${shownYear===i+1?'current':''}`}>{showValue(s)}<small className={c?c.delta<0?'negative':'positive':''}>{c?showDelta(c.delta,c.unit):b?.value==null?'':'unchanged'}</small></td>})}</tr>)}</tbody></table></div></>:needLever,
  x?<><div className="demo-actions"><p>{x.changes.filter(c=>c.year===(year||1)).length} changes in year {year||1}, each attributed to the inputs of its own equation and traced to the lever.</p>{yearChips}</div><div className="ledger">{x.changes.filter(c=>c.year===(year||1)).map(c=><details key={c.node}><summary><span>{c.label}</span><span>{showValue({value:c.base,unit:c.unit})} → {showValue({value:c.scen,unit:c.unit})}</span><b className={c.delta<0?'negative':'positive'}>{showDelta(c.delta,c.unit)}</b></summary><ChangeDetail x={x} c={c} inspect={inspect}/></details>)}{x.absorbed.filter(a=>a.year===(year||1)).map(a=><div className="absorbed" key={a.node}><span>{a.label} · unchanged</span><p>{a.reason}</p></div>)}</div></>:needLever,
 ];
 // Collapsed by default: one line of steps under the machine; any step opens the tour.
 return <section className={`demo-rail ${open?'open':'collapsed'}`} aria-label="Canonical demonstration"><header><span className="eyebrow">GUIDED TOUR / {opening.ticker}</span><nav role="tablist">{steps.map((s,i)=><button key={s} role="tab" aria-selected={open&&step===i} onClick={()=>{setStep(i);setOpen(true)}}><b>{i+1}</b>{s}</button>)}</nav>{open&&<button className="text-button demo-hide" onClick={()=>setOpen(false)}>Hide tour</button>}</header>{open&&<><div className="demo-body">{body[step]}</div><footer><button disabled={step===0} onClick={()=>setStep(step-1)}>Back</button><button disabled={step===steps.length-1} onClick={()=>{if(step===3&&demo&&!x)applyDemo();else if(step===4&&x)run();setStep(step+1)}}>Next: {steps[step+1]||'done'} <ArrowRight size={13}/></button></footer></>}</section>;
}
