import { useEffect, useRef } from 'react';
import { X, ExternalLink } from 'lucide-react';
import type { Baseline, State } from '../model/types';
import { metricInfo, metricFact } from '../model/metadata';
import { money, percent } from '../presentation';
export default function Inspector({metric,state,baseline,history,close}:{metric:string;state:State;baseline:Baseline;history:State[];close:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const info=metricInfo[metric]||{label:metric,formula:'See model inputs',upstream:'User assumptions',downstream:'Model outputs'};const fact=metricFact(metric,state,baseline);
 useEffect(()=>{const el=dialog.current;el?.showModal();return()=>el?.close()},[]);
 const format=(v:number)=>info.unit==='percent'?percent(v):info.unit==='index'?v.toFixed(2):['customers','demand','newCustomers','volume'].includes(metric)?v.toLocaleString('en-GB',{maximumFractionDigits:0}):money(v,baseline.currency);
 const rows=history.map(s=>({year:s.year,value:metricFact(metric,s,baseline).value})).filter(r=>r.value!=null) as {year:number;value:number}[];
 const min=Math.min(0,...rows.map(r=>r.value)),max=Math.max(1,...rows.map(r=>r.value)),span=max-min;
 return <dialog ref={dialog} className="inspector" onCancel={close} onClick={e=>{if(e.target===dialog.current)close()}}><div className="inspector-inner"><header><span className="eyebrow">COMPONENT INSPECTOR</span><button onClick={close} aria-label="Close inspector"><X size={18}/></button></header><h2>{info.label}</h2><div className="inspection-value">{fact.value==null?'Unavailable':format(fact.value)}</div><span className={`data-tag ${fact.status.toLowerCase()}`}>{fact.status}</span><dl><dt>Period</dt><dd>{fact.period}</dd><dt>Source</dt><dd>{fact.url?<a href={fact.url} target="_blank" rel="noreferrer">{fact.source} <ExternalLink size={12}/></a>:fact.source}</dd><dt>Calculation</dt><dd>{fact.calculation||info.formula}</dd><dt>Upstream drivers</dt><dd>{info.upstream}</dd><dt>Downstream effects</dt><dd>{info.downstream}</dd></dl>
 {metric==='businessMomentum'?<section><h3>Why is the machine changing speed?</h3><p className="muted">Index −100 to +100. Each signal is divided by its scale, clipped to ±1 and multiplied by its weight.</p>{state.momentumParts.map(p=><div className="contribution" key={p.label}><div><span>{p.label}</span><strong className={p.contribution<0?'negative':'positive'}>{p.contribution>0?'+':''}{p.contribution.toFixed(2)}</strong></div><div className="contribution-track"><i style={{width:`${Math.abs(p.normalized)*50}%`,left:p.contribution<0?`${50-Math.abs(p.normalized)*50}%`:'50%',background:p.contribution<0?'#a75941':'#5b7851'}}/></div><small>{p.definition} · weight {p.weight*100}%</small></div>)}</section>:rows.length>1?<section><h3>Scenario history</h3><svg className="history-chart" viewBox="0 0 360 155" role="img" aria-label={`${info.label} over years 0 to 10`}><path d="M45 14V125H348" fill="none" stroke="#b9b4a2"/><text x="40" y="19" textAnchor="end">{format(max)}</text><text x="40" y="125" textAnchor="end">{format(min)}</text><polyline points={rows.map(r=>`${45+r.year*29.5},${125-(r.value-min)/span*105}`).join(' ')} fill="none" stroke="#997330" strokeWidth="2.5"/>{[0,5,10].map(t=><text key={t} x={45+t*29.5} y="148" textAnchor="middle">Year {t}</text>)}</svg></section>:null}
 <details><summary>Model assumptions and limitations</summary>{baseline.notes.map(n=><p key={n}>{n}</p>)}<p>Stocks, lags and feedback weights are simplified economic assumptions. This tool does not provide investment recommendations.</p></details></div></dialog>;
}
