import type { SectorModule, Control, CausalEdge, SectorId } from '../ontology/types';
import { equations, refKind, refNode, type Equation } from '../simulation/equations';
const control=(id:string,label:string,min:number,max:number,defaultValue:number,explanation:string,unit:Control['unit']='%',step=unit==='years'||unit==='days'?1:.1):Control=>({id,label,min,max,defaultValue,explanation,unit,step});
// Computed edges are derived from the equation registry; concept edges show the universal backbone and are never simulated.
const concept=(from:string,to:string,formula:string):CausalEdge=>({id:`${from}-${to}-concept`,from,to,formula,lag:0,kind:'concept',relation:'Conceptual link · not simulated'});
export function computedEdges(eqs:Equation[]):CausalEdge[]{const out:CausalEdge[]=[];for(const e of eqs)for(const ref of e.inputs){const from=refNode(ref),kind=refKind(ref);if(!from||kind==='opening')continue;out.push({id:`${from}-${e.target}${kind==='now'?'':'-'+kind}`,from,to:e.target,formula:e.formula,kind:e.kind,lag:kind==='prior'?1:kind==='lagged'?2:0,relation:kind==='prior'?'Carried from the prior year':kind==='lagged'?'Delayed by the adopted investment lag':'Same-year equation'});}return out;}
const computed=(sector:SectorId)=>computedEdges(equations[sector]);
const backbone=[concept('demand','customers','Demand becomes customers; no customer count is reported'),concept('customers','revenue','Customers generate revenue; not separately modeled'),concept('capacity','customerValue','Productive capacity delivers customer value'),concept('customerValue','advantage','Delivered value sustains competitive advantage'),concept('advantage','demand','Advantage renews demand; not quantified')];
const commonControls=[control('growth','Demand / sales growth',-20,25,3,'User assumption for annual sales growth; not an observed demand metric.'),control('marginChange','Margin change',-10,10,0,'Percentage-point change from the opening gross margin; applied once, held thereafter.','pp'),control('opexGrowth','Operating cost growth',-10,25,2,'Annual change in cash and noncash operating expenses.'),control('capexRatio','CapEx / revenue',0,100,10,'Total cash CapEx as a share of revenue; no invented maintenance/growth split.'),control('distribution','Distribution / positive FCF',0,100,25,'Share of positive FCF paid out; negative FCF is not distributed.'),control('cashConversion','Profit change → CFO',0,150,75,'Fraction of the change in operating profit reaching CFO; working-capital movements are included in this aggregate assumption.'),control('investmentLag','Investment delay',1,5,2,'Years before additional CapEx can affect sales.','years'),control('investmentResponse','Investment response',0,50,0,'Sales uplift per unit of extra CapEx / opening revenue, after the lag; zero assumes no automatic benefit.')];
export const sectors:Record<SectorId,SectorModule>={
 'software-cloud':{id:'software-cloud',label:'Software + cloud',gauges:['revenueGrowth','operatingMargin','freeCashFlow','capex','rd','cloudRevenue'],stages:['demand','customers','revenue','grossProfit','operatingProfit','operatingCashFlow','freeCashFlow','capital','capex','capacity','customerValue','advantage'],moduleNodes:['cloudRevenue','rd','ppe','arr','nrr','churn'],controls:commonControls,edges:[...computed('software-cloud'),...backbone,concept('capex','capacity','Investment builds infrastructure; capacity is not measured'),concept('ppe','capacity','Infrastructure book value is not a measured capacity function'),concept('rd','opex','R&D is reported inside operating expense; not projected separately'),concept('cloudRevenue','revenue','Intelligent Cloud is a reported segment of revenue; not projected separately')],limitations:['Software, cloud and personal computing remain a mixed business. No generic SaaS ARR, NRR, CAC or churn is invented.','Forecast cash conversion is a stated sensitivity assumption, not a reconstructed cash-flow statement.','Historical momentum stays UNKNOWN: missing customer and productive-stock observations prevent the full composite.']},
 retail:{id:'retail',label:'Retail + inventory',gauges:['revenueGrowth','operatingMargin','inventoryTurns','inventory','freeCashFlow','capex'],stages:['demand','traffic','revenue','grossProfit','operatingProfit','operatingCashFlow','freeCashFlow','capital','capex','inventory','customerValue','advantage'],moduleNodes:['inventory','inventoryTurns','ppe','stores','traffic'],controls:[...commonControls,control('inventoryDays','Inventory days',10,365,40,'Target closing inventory = annual cost of sales × days / 365. Inventory changes are deducted explicitly from scenario CFO.','days')],edges:[...computed('retail'),...backbone.map(e=>e.from==='demand'?concept('demand','traffic','Demand arrives as store and online traffic; not reported'):e.from==='customers'?concept('traffic','revenue','Traffic × conversion × basket = sales; components not reported'):e),concept('capex','capacity','Stores, fulfilment and technology capacity; not measured'),concept('ppe','capacity','Property book value is not a measured capacity function')],limitations:['Retail total-revenue gross margin includes membership and other income; it is not the reported net-sales gross profit rate.','Forecast inventory cash movements are separated from aggregate cash conversion. Payables and other working-capital effects remain within the explicit conversion assumption.','Store count, customer traffic and conversion are UNKNOWN when not supplied.']},
 banking:{id:'banking',label:'Banking + credit',gauges:['revenueGrowth','nii','provision','loanDeposit','cet1','lcr'],stages:['demand','deposits','loans','nii','fees','revenue','provision','netIncome','retainedProfit','capital','customerValue','advantage'],moduleNodes:['deposits','loans','nii','provision','cet1','lcr'],controls:[control('loanGrowth','Loan growth',-20,25,3,'Annual change in loan balances; applies to earning assets in this simplified sensitivity.'),control('depositGrowth','Deposit growth',-20,25,3,'Annual change in deposit funding; funding gaps are exposed rather than auto-funded.'),control('niiChange','NII rate sensitivity',-30,30,0,'One-time proportional adjustment to baseline NII yield. Not a full interest-rate or NIM forecast.'),control('creditCost','Credit provision / loans',-2,8,1,'Annual provision expense / average loans; not realized cash charge-offs. Negative means a reserve release, as some banks reported.','%',.05),control('feeGrowth','Noninterest revenue growth',-20,25,3,'Annual change in noninterest revenue, including trading and fees.'),control('opexGrowth','Operating cost growth',-10,25,2,'Annual change in bank noninterest expense.'),control('taxRate','Scenario tax rate',0,50,25,'Applied to positive pretax income; no automatic tax benefit from losses.'),control('payout','Profit payout',0,100,30,'Share of positive net income distributed; retained income is not asserted to equal CET1 capital.')],edges:[...computed('banking'),concept('demand','deposits','Client demand appears as deposits and borrowing; not modeled'),concept('deposits','loans','Deposits fund assets; loan and deposit growth are independent assumptions here'),concept('retainedProfit','capital','Retained earnings feed CET1 only after regulatory adjustments; not simulated'),concept('capital','customerValue','Capital strength supports lending capacity and client trust'),concept('customerValue','advantage','Delivered value sustains competitive advantage'),concept('advantage','demand','Advantage renews demand; not quantified')],limitations:['Bank FCF, industrial gross margin and industrial ROIC are not used.','Bank scenarios are earnings and funding sensitivities, not a full balance-sheet, cash-liquidity or regulatory-capital forecast.','Future CET1, LCR and regulatory capital stay UNKNOWN without the required regulatory components.','Deposit outflows are not equated with a loss of revenue. Credit provisions are not treated as cash charge-offs.']},
 general:{id:'general',label:'General company',gauges:['revenueGrowth','operatingMargin','grossMargin','freeCashFlow','capex','rd'],stages:['demand','customers','revenue','grossProfit','operatingProfit','operatingCashFlow','freeCashFlow','capital','capex','capacity','customerValue','advantage'],moduleNodes:['ppe','rd','inventory'],controls:commonControls,edges:[...computed('general'),...backbone,concept('capex','capacity','Investment builds productive assets; capacity is not measured'),concept('ppe','capacity','Property and equipment book value is not a measured capacity function'),concept('rd','opex','R&D is reported inside operating expense; not projected separately')],limitations:['Universal economic core only: no sector module covers this industry yet, so segment, product and customer economics are not modeled.','Built automatically from SEC XBRL annual facts. Figures that are not tagged consistently stay UNKNOWN.','Forecast cash conversion is a stated sensitivity assumption, not a reconstructed cash-flow statement.']},
};
/** The controls a machine actually uses. On a total-cost basis there is no separate operating expense line, so its growth
 * lever does not apply, and the margin lever moves total costs as a share of revenue. */
export function controlsFor(m:{costBasis?:'total';inventoryBasis?:'reported';classification:{sector:SectorId}}):Control[]{
 const all=sectors[m.classification.sector].controls.filter(c=>!(c.id==='inventoryDays'&&(m.inventoryBasis==='reported'||m.costBasis==='total')));
 return m.costBasis!=='total'?all:all.filter(c=>c.id!=='opexGrowth').map(c=>c.id==='marginChange'?{...c,explanation:'Percentage-point change from the opening operating margin, i.e. total costs as a share of revenue; applied once, held thereafter.'}:c);
}
