// Canonical end-to-end demonstration: reported data → machine → causal model → one lever → propagation →
// five-year simulation → explanation of every change. `npm run demo -- MSFT` prints; `--write` updates docs/demos.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { constructMachine, getNode } from '../src/translation/construct';
import { sectors } from '../src/sectors';
import { equations } from '../src/simulation/equations';
import { HORIZON, suggestedBasis } from '../src/simulation/company';
import { demoScenarios } from '../src/simulation/demos';
import { describeChange, describeLever, explainExperiment, isLeverRef, rootPath } from '../src/simulation/explain';
import { showDelta, showValue } from '../src/format';
import type { CompanyDataset } from '../src/ontology/types';

export function transcript(ticker: string): string {
 const dataset = JSON.parse(readFileSync(`public/machines/${ticker}.json`, 'utf8')) as CompanyDataset;
 const m = constructMachine(dataset), module = sectors[m.classification.sector], { demo, base, lever } = demoScenarios(m);
 const x = explainExperiment(m, base, lever), basis = suggestedBasis(m), out: string[] = [];
 const cell = (s: string) => s.replace(/\|/g, '\\|');
 out.push(`# ${m.name} (${ticker}) — canonical demonstration`, '', `Generated by \`npm run demo -- ${ticker} --write\` from \`public/machines/${ticker}.json\`. Every number below is recomputed from the published dataset and the equation registry; nothing is hand-written.`, '');
 out.push(`## 1. Reported data — FY${m.fiscalYear} (period ending ${m.period})`, '', '| Component | Value | Status | Source |', '| --- | --- | --- | --- |');
 for (const n of m.nodes.filter(n => (n.status === 'OBSERVED' || (n.status === 'CALCULATED' && n.inputs)) && !(n.id === 'capital' && m.classification.sector !== 'banking'))) out.push(`| ${n.label} | ${showValue(n)} | ${n.status} | ${n.url ? `[${cell(n.source)}](${n.url})` : cell(n.calculation || n.source)} |`);
 out.push('', `## 2. Economic machine — ${module.label}`, '', `**Why this machine?** ${m.classification.rationale}`, '', `Ring (universal core + sector stages): ${m.stages.map(s => getNode(m, s)?.label).join(' → ')}.`, '', `Sector module: ${m.moduleNodes.map(s => `${getNode(m, s)?.label} (${showValue(getNode(m, s))})`).join(', ')}.`, '');
 out.push(`${m.nodes.filter(n => n.value != null).length} of ${m.nodes.length} components have values. UNKNOWN components are shown as gaps, never filled: ${m.nodes.filter(n => n.value == null).map(n => n.label).join(', ')}.`, '');
 out.push('## 3. Causal model — the forecast equations', '', 'The simulator evaluates these rows in order each year; the machine’s computed links are generated from their inputs.', '', '| # | Component | Equation | Type |', '| --- | --- | --- | --- |');
 equations[m.classification.sector].forEach((e, i) => out.push(`| ${i + 1} | ${getNode(m, e.target)?.label || e.target} | ${cell(e.formula)} | ${e.kind} |`));
 out.push('', `Conceptual links (drawn, never simulated): ${m.edges.filter(e => e.kind === 'concept').map(e => `${getNode(m, e.from)?.label} → ${getNode(m, e.to)?.label}`).join('; ')}.`, '');
 out.push('## 4. One lever', '', `**${demo.question}**`, '', demo.why, '', `Lever: **${x.levers.map(describeLever).join('; ')}**. All other assumptions are identical in BASE and LEVER:`, '', '| Assumption | Value | Basis |', '| --- | --- | --- |');
 for (const c of module.controls) out.push(`| ${c.label} | ${base.values[c.id]} ${c.unit}${c.id === demo.lever ? ` → **${lever.values[c.id]} ${c.unit}**` : ''} | ${basis[c.id] || 'Neutral placeholder; not a company disclosure'} |`);
 out.push('', '## 5. Propagation — year 1, in causal order', '');
 x.changes.filter(c => c.year === 1).forEach((c, i) => out.push(`${i + 1}. **${c.label}** ${showDelta(c.delta, c.unit)} — via ${c.contributions.map(p => p.label).join(', ')}`));
 const absorbed1 = x.absorbed.filter(a => a.year === 1);
 if (absorbed1.length) out.push('', 'Reached but unchanged:', '', ...absorbed1.map(a => `- **${a.label}** — ${a.reason}`));
 out.push('', `## 6. Five-year simulation — BASE vs LEVER`, '', `| Component | ${Array.from({ length: HORIZON }, (_, i) => `Y${i + 1}`).join(' | ')} |`, `| --- |${' --- |'.repeat(HORIZON)}`);
 for (const id of demo.watch) out.push(`| ${getNode(m, id)?.label} | ${Array.from({ length: HORIZON }, (_, i) => { const b = getNode(x.base[i + 1], id), s = getNode(x.scen[i + 1], id); const d = b?.value != null && s?.value != null ? s.value - b.value : 0; return `${showValue(s)}${Math.abs(d) > 1e-9 * Math.max(1, Math.abs(b?.value || 0)) ? ` (${showDelta(d, s!.unit)})` : ''}`; }).join(' | ')} |`);
 out.push('', 'Values are the LEVER run; brackets show the difference from BASE. No bracket means unchanged.', '');
 out.push('## 7. Every resulting change, explained', '');
 for (let y = 1; y <= HORIZON; y++) {
  out.push(`### Year ${y}`, '');
  for (const c of x.changes.filter(c => c.year === y)) out.push(`- ${describeChange(x, c)}`);
  for (const a of x.absorbed.filter(a => a.year === y)) out.push(`- *Unchanged:* **${a.label}** — ${a.reason}`);
  out.push('');
 }
 const worst = Math.max(0, ...x.changes.map(c => Math.abs(c.delta - c.contributions.reduce((t, p) => t + p.effect, 0) - c.interaction)));
 const rooted = x.changes.filter(c => { const last = rootPath(x, c).at(-1)!; return 'ref' in last && isLeverRef(last.ref); }).length;
 out.push('## 8. Reconciliation', '', `- ${x.changes.length} component-years changed; ${rooted} trace back to the lever (${rooted === x.changes.length ? 'all' : 'NOT ALL'}).`, `- Largest unexplained residual after input effects and interaction: ${worst.toExponential(1)}.`, `- Interaction terms (non-additive effects) appear in ${x.changes.filter(c => c.interaction).length} of ${x.changes.length} explanations.`, `- Reported FY${m.fiscalYear} values are unchanged; both runs fork from the same opening state.`, '');
 return out.join('\n');
}
const args = process.argv.slice(2), write = args.includes('--write'), tickers = args.filter(a => !a.startsWith('--'));
for (const t of tickers.length ? tickers.map(t => t.toUpperCase()) : ['MSFT', 'WMT', 'JPM']) {
 const text = transcript(t);
 if (write) { mkdirSync('docs/demos', { recursive: true }); writeFileSync(`docs/demos/${t}.md`, text); console.log(`Wrote docs/demos/${t}.md`); } else console.log(text);
}
