import { useEffect, useMemo, useRef, useState, type ChangeEvent } from 'react';
import { Play, Pause, RotateCcw, SkipForward, ArrowRight, Settings2, Download, Upload, Columns2, Zap, Info, VolumeX } from 'lucide-react';
import Machine from './components/Machine';
import Gauge from './components/Gauge';
import Inspector from './components/Inspector';
import { manualBaseline, companyBaseline } from './model/baseline';
import { simulate, shockLabels } from './model/engine';
import { allocationKeys, type AllocationKey, type Assumptions, type Baseline, type ScenarioName, type ShockKind, type State } from './model/types';
import { machineView, money, percent } from './presentation';
import { initialScenarios, loadScenarios, scenarioNames, validateScenarios, limits } from './state';
import { StaticFinancialDataProvider } from './data/provider';
import { metricFact } from './model/metadata';

const provider=new StaticFinancialDataProvider();
const allocationLabels:Record<AllocationKey,string>={rd:'R&D',product:'Product',people:'People',marketing:'Marketing',sales:'Sales',infrastructure:'Infrastructure',automation:'Automation',maintenance:'Maintenance',acquisitions:'Acquisitions',debtRepayment:'Debt repayment',dividends:'Dividends',reserves:'Cash reserves'};
const moreControls: [Exclude<keyof Assumptions,'allocations'>,string,number][]=[['priceGrowth','Annual price growth',100],['opexRatio','Cash operating cost ratio',100],['interestRate','Interest rate',100],['taxRate','Tax rate',100],['maintenanceRatio','Maintenance CapEx / sales',100],['productivityGrowth','Productivity growth',100],['costOfCapital','Cost of capital',100],['workingCapitalRatio','Working capital / sales',100],['depreciationRate','Asset decay / depreciation',100],['investmentLag','Investment lag (years)',1],['investmentEfficiency','Investment efficiency',100],['competition','Competition pressure',100]];
const compareMetrics:[keyof State,string,string?][]=[['revenue','Revenue'],['operatingProfit','Operating profit'],['freeCashFlow','Free cash flow'],['cash','Cash reserve'],['debt','Debt'],['roic','ROIC','percent'],['productiveCapacity','Capacity','index'],['businessMomentum','Momentum','index']];

export default function ManualApp({onCompany}:{onCompany:(ticker:string)=>void}){
 const [baseline,setBaseline]=useState<Baseline>(()=>manualBaseline());
 const [scenarios,setScenarios]=useState(()=>loadScenarios(baseline));
 const [active,setActive]=useState<ScenarioName>('CUSTOM');
 const [year,setYear]=useState(0);const [playing,setPlaying]=useState(false);const [motion,setMotion]=useState(true);
 const [ticker,setTicker]=useState('');const [loading,setLoading]=useState(false);const [message,setMessage]=useState('');
 const [inspect,setInspect]=useState<string|null>(null);const [advanced,setAdvanced]=useState(false);const [compare,setCompare]=useState(false);
 const [shock,setShock]=useState<ShockKind>('demand');const [cascade,setCascade]=useState(false);const [manualEdit,setManualEdit]=useState(false);
 const importRef=useRef<HTMLInputElement>(null);const loadSerial=useRef(0);
 const scenario=scenarios[active];const a=scenario.assumptions;
 const histories=useMemo(()=>Object.fromEntries(scenarioNames.map(n=>[n,simulate(baseline,scenarios[n])])) as Record<ScenarioName,State[]>,[baseline,scenarios]);
 const history=histories[active],s=history[year],base=histories.BASE[year],view=machineView(s,baseline);
 useEffect(()=>{try{localStorage.setItem(`gcm:v1:${baseline.id}`,JSON.stringify({version:1,baselineId:baseline.id,scenarios}));}catch{/* Optional persistence. */}},[baseline.id,scenarios]);
 useEffect(()=>{if(!playing)return;const timer=window.setInterval(()=>setYear(y=>{if(y>=10){setPlaying(false);return 10}return y+1}),1100);return()=>clearInterval(timer)},[playing]);
 useEffect(()=>{if(!cascade)return;const timer=window.setTimeout(()=>setCascade(false),5000);return()=>clearTimeout(timer)},[cascade]);
 const swapBaseline=(b:Baseline)=>{setBaseline(b);setScenarios(loadScenarios(b));setYear(0);setPlaying(false);setActive('CUSTOM');setMessage('');};
 function changeAssumption(key:Exclude<keyof Assumptions,'allocations'>,value:number){
  const target=active==='BASE'?'CUSTOM':active;const [lo,hi]=limits[key];
  setScenarios(old=>({...old,[target]:{...old[target],assumptions:{...old[target].assumptions,[key]:Math.max(lo,Math.min(hi,value))}}}));
  setActive(target);if(year===0)setYear(1);setPlaying(false);if(key==='churn')setCascade(true);
 }
 function changeAllocation(key:AllocationKey,value:number){const target=active==='BASE'?'CUSTOM':active;setScenarios(old=>({...old,[target]:{...old[target],assumptions:{...old[target].assumptions,allocations:{...old[target].assumptions.allocations,[key]:value}}}}));setActive(target);if(year===0)setYear(1);setPlaying(false);}
 async function loadCompany(e?:React.FormEvent){e?.preventDefault();onCompany(ticker.trim().toUpperCase());}
 function reset(){setScenarios(old=>({...old,[active]:initialScenarios(baseline)[active]}));setYear(0);setPlaying(false);setMessage('Scenario reset to the opening baseline.');}
 function inject(){if(year===10){setMessage('Move to an earlier year to inject a shock.');return;}const target=active==='BASE'?'CUSTOM':active;if(scenarios[target].shocks.length>=30){setMessage('Limit reached: reset this scenario before adding more shocks.');return;}setScenarios(old=>({...old,[target]:{...old[target],shocks:[...old[target].shocks,{id:crypto.randomUUID(),kind:shock,year:Math.max(1,year+1)}]}}));setActive(target);setYear(y=>Math.min(10,y+1));setCascade(true);setMessage(`${shockLabels[shock]} applied from year ${Math.max(1,year+1)} onward.`);}
 function exportFile(){const blob=new Blob([JSON.stringify({version:1,baselineId:baseline.id,scenarios},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`going-concern-${baseline.id}-scenarios.json`;link.click();URL.revokeObjectURL(url);}
 async function importFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;try{if(file.size>100000)throw new Error('Scenario file is too large.');const data=JSON.parse(await file.text());if(data.version!==1||!validateScenarios(data.scenarios))throw new Error('Invalid scenario file.');if(data.baselineId!==baseline.id)throw new Error(`Load ${data.baselineId} before importing these scenarios.`);setScenarios({...data.scenarios,BASE:initialScenarios(baseline).BASE});setActive('CUSTOM');setYear(1);setMessage('Scenarios imported.');}catch(error){setMessage(error instanceof Error?error.message:'Could not import file.')}event.target.value='';}
 const detail=(key:string)=>{const f=metricFact(key,s,baseline);return `${f.status} · ${f.period} · ${f.source} · ${f.calculation||'Open inspector for calculation'}`};
 function control(key:Exclude<keyof Assumptions,'allocations'>,label:string,scale=100){const [lo,hi]=limits[key];return <label className="slider-control" key={key}><span>{label}<output>{scale===100?`${(a[key]*100).toFixed(1)}%`:a[key].toFixed(0)}</output></span><input aria-label={label} type="range" min={lo*scale} max={hi*scale} step={key==='investmentLag'?1:.5} value={a[key]*scale} onChange={e=>changeAssumption(key,+e.target.value/scale)}/></label>}
 function saveManual(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const b=manualBaseline();const revenue=Number(f.get('revenue'))*1e6;const factor=revenue/b.state.revenue;
  for(const key of ['revenue','cogs','grossProfit','opex','operatingProfit','depreciation','tax','interestExpense','workingCapital','maintenanceCapex','growthCapex','operatingCashFlow','freeCashFlow','investment'] as const)b.state[key]*=factor;
  b.state.price=revenue/b.state.customers;b.assumptions.cac*=factor;b.state.cac=b.assumptions.cac;b.state.cash=Number(f.get('cash'))*1e6;b.state.availableCapital=b.state.cash;b.state.debt=Number(f.get('debt'))*1e6;b.state.investedCapital=Number(f.get('capital'))*1e6;b.state.equity=b.state.investedCapital+b.state.cash-b.state.debt;
  for(const k of Object.keys(b.state.stocks) as (keyof typeof b.state.stocks)[])b.state.stocks[k]*=b.state.investedCapital/8e6;
  b.state.interestExpense=b.state.debt*b.assumptions.interestRate;b.state.tax=Math.max(0,b.state.operatingProfit-b.state.interestExpense)*b.assumptions.taxRate;b.state.operatingCashFlow=b.state.operatingProfit-b.state.tax-b.state.interestExpense+b.state.depreciation;b.state.freeCashFlow=b.state.operatingCashFlow-b.state.maintenanceCapex-b.state.growthCapex;b.state.roic=b.state.operatingProfit*(1-b.assumptions.taxRate)/b.state.investedCapital;b.state.capitalTurnover=b.state.revenue/b.state.investedCapital;
  b.name=String(f.get('name')||'Your hypothetical business');setBaseline(b);setScenarios(initialScenarios(b));setYear(0);setActive('CUSTOM');setManualEdit(false);setPlaying(false);setMessage('Manual business configured.');
 }
 return <main className="app-shell">
  <header className="masthead"><div className="brand"><div className="edition">ECONOMIC SYSTEMS LAB <span>EST. 2026 / MODEL 01</span></div><h1>The Going Concern Machine</h1><p>A dynamic model of business continuity, growth & decay</p></div><form className="ticker-form" onSubmit={loadCompany}><label htmlFor="ticker">LOAD A BUSINESS</label><div><input id="ticker" value={ticker} onChange={e=>setTicker(e.target.value.toUpperCase())} placeholder="MSFT, WMT, JPM" maxLength={10}/><button disabled={loading} type="submit">{loading?'Loading…':'Load'} <ArrowRight size={14}/></button></div><span>Sector-specific company models · <button type="button" onClick={()=>{loadSerial.current++;setLoading(false);swapBaseline(manualBaseline());setTicker('')}}>Manual mode</button></span></form></header>
  <section className="management-console" aria-label="Management allocation console"><div className="console-heading"><span className="screw"/> <h2>MANAGEMENT / CAPITAL ALLOCATION</h2><button className="text-button" onClick={()=>setInspect('investment')}>Relative budget weights <Info size={12}/></button><span className="screw"/></div><div className="allocation-bank">{allocationKeys.map(k=><label className="allocation-lever" key={k}><span className="lever-case"><input aria-label={`${allocationLabels[k]} allocation`} type="range" min="0" max="100" value={a.allocations[k]} onChange={e=>changeAllocation(k,+e.target.value)}/></span><span>{allocationLabels[k]}</span><output>{a.allocations[k]}</output></label>)}<div className="master-lever">{control('reinvestmentRate','REINVESTMENT RATE')}<small>Productive investment<br/>from available cash generation</small></div></div></section>
  <section className="business-bar"><div><span className={`status-light ${view.stress?'red':''}`}/><strong>{baseline.name}{baseline.company?` — ${baseline.id}`:''}</strong><span>{baseline.company?`FY${baseline.company.statements[0].fiscalYear} · ${baseline.period}`:'HYPOTHETICAL / USER ASSUMPTIONS'}</span></div><div><span className="data-tag">{year===0?'OPENING BASELINE':`SCENARIO YEAR ${year}`}</span><button className="text-button" onClick={()=>setManualEdit(v=>!v)}>Configure manual business</button></div></section>
  {message&&<div className="notice" role="status">{message}<button onClick={()=>setMessage('')} aria-label="Dismiss message">×</button></div>}
  {manualEdit&&<form className="manual-editor" onSubmit={saveManual}><h3>Configure a hypothetical business</h3><label>Name<input name="name" defaultValue="My business" maxLength={70} required/></label>{[['revenue','Annual revenue (£m)',10],['cash','Cash (£m)',3.8],['debt','Debt (£m)',3],['capital','Invested capital (£m)',8]].map(([k,label,v])=><label key={k}>{label}<input name={String(k)} type="number" min={k==='revenue'||k==='capital'?.1:0} max="1000000" step=".1" defaultValue={v} required/></label>)}<button type="submit">Create business</button><button type="button" onClick={()=>setManualEdit(false)}>Cancel</button></form>}
  <div className={`workspace ${compare?'compare-mode':''}`}>
   <section className="machine-main">{compare&&<div className="compare-machine-title">{active} SCENARIO</div>}<Machine state={s} baseline={baseline} view={view} motion={motion} inspect={setInspect} cascade={cascade}/>{cascade&&<div className="cascade-label">CAUSAL PATH · Demand / churn → customers → revenue → cash → investment</div>}</section>
   {compare?<section className="comparison-machine"><div className="compare-machine-title">BASE SCENARIO / SAME YEAR</div><Machine state={base} baseline={baseline} view={machineView(base,baseline)} motion={motion} inspect={key=>{setActive('BASE');setInspect(key)}} compact/></section>:<aside className="instrument-panel"><h2 className="ribbon">KEY OPERATING GAUGES</h2><div className="gauges"><Gauge label="Gross margin" value={percent(s.grossMargin)} level={s.grossMargin} detail={detail('grossMargin')} onClick={()=>setInspect('grossMargin')}/><Gauge label="Retention¹" value={percent(s.retention)} level={s.retention} detail={detail('retention')} onClick={()=>setInspect('retention')}/><Gauge label="ROIC" value={percent(s.roic)} level={s.roic/.5} negative={s.roic<s.costOfCapital} detail={detail('roic')} onClick={()=>setInspect('roic')}/><Gauge label="Cost of capital¹" value={percent(s.costOfCapital)} level={s.costOfCapital/.3} detail="USER ASSUMPTION · Future discount / financing hurdle" onClick={()=>setAdvanced(true)}/><Gauge label="Cash / year" value={money(s.freeCashFlow,baseline.currency)} level={Math.max(0,s.freeCashFlow/s.revenue)*2} negative={s.freeCashFlow<0} detail={detail('freeCashFlow')} onClick={()=>setInspect('freeCashFlow')}/><Gauge label="Capacity index¹" value={`${s.productiveCapacity.toFixed(2)}×`} level={s.productiveCapacity/2} detail={detail('productiveCapacity')} onClick={()=>setInspect('productiveCapacity')}/></div><p className="gauge-footnote">¹ Model assumptions, not reported facts.</p><h2 className="ribbon">VALUE CREATION CONDITION</h2><button className={`value-condition ${s.roic<s.costOfCapital?'destruction':''}`} onClick={()=>setInspect('roic')}><strong>ROIC {s.roic>=s.costOfCapital?'≥':'<'} cost of capital</strong><span>{s.roic>=s.costOfCapital?'VALUE CREATION':'CAPITAL DESTRUCTION'}</span></button><p className="liquidity-status">{view.liquidity}<br/><span>Liquidity is separate from profitability.</span></p><h2 className="ribbon">SCENARIO / YEAR {year}</h2><table className="mini-comparison"><thead><tr><th></th><th>BASE</th><th>{active}</th></tr></thead><tbody>{compareMetrics.slice(0,4).map(([k,label])=><tr key={k}><th>{label}</th><td>{money(base[k] as number,baseline.currency)}</td><td>{money(s[k] as number,baseline.currency)}</td></tr>)}</tbody></table><button className="text-button full" onClick={()=>setInspect('businessMomentum')}>Why is the machine {s.businessMomentum>5?'accelerating':'slowing'}? <ArrowRight size={13}/></button></aside>}
  </div>
  <section className="scenario-controls"><div className="controls-heading"><h2>SCENARIO CONTROLS <span>/ CHANGE THE INPUTS, WATCH THE MACHINE</span></h2><button onClick={()=>setAdvanced(v=>!v)} className="text-button"><Settings2 size={14}/>{advanced?'Fewer controls':'All assumptions'}</button></div><div className="primary-controls">{control('demandGrowth','Demand growth')}{control('churn','Customer churn')}{control('grossMargin','Gross margin')}{control('reinvestmentRate','Reinvestment rate')}{control('productivityGrowth','Productivity growth')}</div>{advanced&&<div className="advanced-controls">{moreControls.map(([k,label,scale])=>control(k,label,scale))}<label className="number-control">CAC {baseline.company?'(activity-index unit)':''}<input type="number" min=".01" max="1000000000000" step="1" value={a.cac.toFixed(2)} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber))changeAssumption('cac',e.target.valueAsNumber)}}/></label><p>Year 0 is preserved. Changing an assumption shows year 1. Forecasts are simplified scenarios, not predictions.</p></div>}</section>
  <section className="transport"><div className="playback"><button className="primary-button" onClick={()=>{if(year===10)setYear(0);setPlaying(v=>!v)}}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'Pause':'Play'}</button><button onClick={()=>{setPlaying(false);setYear(y=>Math.min(10,y+1))}} disabled={year===10} aria-label="Step forward"><SkipForward size={16}/></button><button onClick={reset}><RotateCcw size={14}/> Reset</button><button onClick={()=>{setYear(0);setPlaying(true)}} className="run-button">Run 10 years</button></div><label className="timeline"><span>YEAR <strong>{year}</strong><span>10</span></span><input aria-label="Simulation year" type="range" min="0" max="10" step="1" value={year} onChange={e=>{setPlaying(false);setYear(+e.target.value)}}/></label><div className="scenario-tabs" role="group" aria-label="Scenario containers">{scenarioNames.map(n=><button key={n} aria-pressed={active===n} onClick={()=>{setActive(n);setPlaying(false)}}>{n}</button>)}</div><button className={compare?'selected':''} onClick={()=>setCompare(v=>!v)} title="Compare two machines" aria-label="Compare two machines"><Columns2 size={17}/></button></section>
  <section className="workbench"><div className="shock-controls"><Zap size={15}/><label htmlFor="shock">INJECT SHOCK</label><select id="shock" value={shock} onChange={e=>setShock(e.target.value as ShockKind)}>{Object.entries(shockLabels).map(([k,label])=><option key={k} value={k}>{label}</option>)}</select><button onClick={inject} disabled={year===10}>Apply in year {Math.min(10,year+1)}</button>{scenario.shocks.length>0&&<button className="text-button" onClick={()=>{setScenarios(old=>({...old,[active]:{...old[active],shocks:[]}}));setMessage('Shocks cleared.')}}>Clear {scenario.shocks.length} shocks</button>}</div><div className="file-controls"><button onClick={()=>setMotion(v=>!v)} aria-pressed={!motion}><VolumeX size={14}/>{motion?'Reduce motion':'Restore motion'}</button><button onClick={exportFile}><Download size={14}/>Export</button><button onClick={()=>importRef.current?.click()}><Upload size={14}/>Import</button><input ref={importRef} type="file" accept=".json,application/json" hidden onChange={importFile}/></div></section>
  <details className="comparison-table"><summary>Compare all scenarios · year {year}</summary><div className="table-scroll"><table><thead><tr><th>Measure</th>{scenarioNames.map(n=><th key={n}>{n}</th>)}</tr></thead><tbody>{compareMetrics.map(([k,label,unit])=><tr key={k}><th>{label}</th>{scenarioNames.map(n=><td key={n}>{unit==='percent'?percent(histories[n][year][k] as number):unit==='index'?(histories[n][year][k] as number).toFixed(2):money(histories[n][year][k] as number,baseline.currency)}</td>)}</tr>)}</tbody></table></div><p>BASE uses opening assumptions. BULL and BEAR start identical; you choose their assumptions.</p></details>
  <footer className="page-footer"><span>THE MACHINE CONTINUES ONLY WHILE IT CREATES, CAPTURES AND REINVESTS ENOUGH ECONOMIC VALUE.</span><button className="text-button" onClick={()=>setInspect('businessMomentum')}>Model & sources</button></footer>
  {baseline.company&&<p className="source-note">Annual snapshot · {baseline.company.provider} · retrieved {baseline.company.updated.slice(0,10)} · not live or TTM data. <button className="text-button" onClick={()=>setInspect('revenue')}>View source</button></p>}
  {inspect&&<Inspector metric={inspect} state={s} baseline={baseline} history={history} close={()=>setInspect(null)}/>}
 </main>;
}
